### ISSUE TITLE
小白部署教程

### ISSUE THREAD

**Issue by zy111x** [oiov/iconce#2]
一人血书请求大佬出个部署教程，excel那个源项目没看懂

**Comment by zy111x** [comment]
![image](https://github.com/user-attachments/assets/106d4e50-397b-4edd-91f7-aa2e24eef22f)
vercel部署是这样

**Comment by zy111x** [comment]
![image](https://github.com/user-attachments/assets/1947b44a-289f-4ca9-a4f4-1362c9fa39af)
错误日志

**Comment by oiov** [comment]
原模板要简单一点呀，我是在他基础上还改了逻辑的
